#!/bin/bash

. /etc/os-release

usermod -c "$NAME User" liveuser
hostnamectl hostname "$ID"

timedatectl set-timezone UTC
ln -s /usr/share/zoneinfo/UTC /etc/localtime

if [ -d /var/lib/livesys/livesys-session-extra.d ]; then
  find /var/lib/livesys/livesys-session-extra.d -type f -exec /bin/bash {} \;
fi
